replicaCount: 3

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 8080

autoscaling:
  enabled: false

nginx:
  conf:
    message: "CodeWizard Helm Demo"
